# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/windows10/Documents/Tencent Files/2937572301/FileRecv/2018级实验/实验1/constr/constr.xdc

# IP: C:/Users/windows10/Desktop/vivadoWorks/memories/memories.srcs/sources_1/ip/instruction_rom/instruction_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==instruction_rom || ORIG_REF_NAME==instruction_rom}]
