# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.cache/wt [current_project]
set_property parent.project_path C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files C:/Users/windows10/Desktop/vivadoWorks/data_ram/data_ram.srcs/sources_1/ip/ram.coe
add_files C:/Users/windows10/Desktop/vivadoWorks/Project_II/ram.coe
add_files {{C:/Users/windows10/Documents/Tencent Files/2937572301/FileRecv/2018级实验/实验3/coe/mipstest.coe}}
read_ip C:/Users/windows10/Desktop/vivadoWorks/memories/memories.srcs/sources_1/ip/instruction_rom/instruction_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/windows10/Desktop/vivadoWorks/memories/memories.srcs/sources_1/ip/instruction_rom/instruction_rom_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/windows10/Desktop/vivadoWorks/memories/memories.srcs/sources_1/ip/instruction_rom/instruction_rom.dcp]
set_property is_locked true [get_files C:/Users/windows10/Desktop/vivadoWorks/memories/memories.srcs/sources_1/ip/instruction_rom/instruction_rom.xci]

read_verilog -library xil_defaultlib {
  C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.srcs/sources_1/new/seg7.v
  C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.srcs/sources_1/new/maindec.v
  C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.srcs/sources_1/new/aludec.v
  C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.srcs/sources_1/new/pc_adder.v
  C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.srcs/sources_1/new/pc.v
  C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.srcs/sources_1/new/display.v
  C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.srcs/sources_1/new/controller.v
  C:/Users/windows10/Desktop/vivadoWorks/Project_II/Project_II.srcs/sources_1/new/top.v
}
read_xdc {{C:/Users/windows10/Documents/Tencent Files/2937572301/FileRecv/2018级实验/实验1/constr/constr.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/windows10/Documents/Tencent Files/2937572301/FileRecv/2018级实验/实验1/constr/constr.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7a100tcsg324-3
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
