# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.cache/wt [current_project]
set_property parent.project_path C:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip c:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.srcs/sources_1/ip/data_ram/data_ram.xci
set_property is_locked true [get_files c:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.srcs/sources_1/ip/data_ram/data_ram.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top data_ram -part xc7a100tcsg324-3 -mode out_of_context
rename_ref -prefix_all data_ram_
write_checkpoint -noxdef data_ram.dcp
catch { report_utilization -file data_ram_utilization_synth.rpt -pb data_ram_utilization_synth.pb }
if { [catch {
  file copy -force C:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.runs/data_ram_synth_1/data_ram.dcp c:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.srcs/sources_1/ip/data_ram/data_ram.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub c:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.srcs/sources_1/ip/data_ram/data_ram_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.srcs/sources_1/ip/data_ram/data_ram_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim c:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.srcs/sources_1/ip/data_ram/data_ram_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim c:/Users/windows10/Desktop/vivadoWorks/Mems/Mems.srcs/sources_1/ip/data_ram/data_ram_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
